/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface OnFillInput {
  actions: Array<OrderInput>
}
export interface OrderInput {
  type: string
  symbol?: string
  isBuy?: boolean
  price?: number
  size?: number
  reduceOnly?: boolean
  iso?: boolean
  builderCode?: BuilderCodeInput
  orderType?: OrderTypeInput
  clientId?: string
  orderId?: string
  amount?: number
  symbols?: Array<string>
  triggerPrice?: number
  limitPrice?: number
  pmin?: number
  pmax?: number
  lmin?: number
  lmax?: number
  actions?: Array<OrderInput>
  onFill?: OnFillInput
  trailBps?: number
  stepBps?: number
}
export interface BuilderCodeInput {
  to: string
  fee: number
}
export interface OrderTypeInput {
  type: string
  tif?: string
  isMarket?: boolean
  triggerPx?: number
}
export interface LeverageSetting {
  symbol: string
  leverage: number
}
export interface LiquidatorInstrumentInput {
  symbol: string
  maxExposure: number
  reserve: number
  rfactor: number
  volumePercent: number
  volumeMin: number
  volumeRampup: number
  maxSweepBps: number
  maxAdlNotional: number
  maxAdlPercent: number
}
export interface LiquidatorConfigInput {
  crossExposure: number
  scoringSkew: number
  toxicity: number
  urgencySizeFraction: number
  sweepSds: number
  instruments: Array<LiquidatorInstrumentInput>
}
export interface OraclePriceInput {
  timestamp: number
  asset: string
  price: number
}
export interface PythOraclePriceInput {
  timestamp: number
  feedIndex: number
  price: number
  exponent: number
}
export interface SignedTransactionOutput {
  /** Actions JSON as string */
  actions: string
  /** Nonce */
  nonce: string
  /** Account public key (base58) */
  account: string
  /** Signer public key (base58) */
  signer: string
  /** Signature (base58) */
  signature: string
  /**
   * Pre-computed order ID for single-order transactions (base58).
   * Computed from BULK-SDK canonical action bytes.
   */
  orderId?: string
  /** Optional pre-computed order IDs for multi-order transactions. */
  orderIds?: Array<string>
}
/** Generate a random hash (for client order IDs) */
export declare function randomHash(): string
/** Get the current Unix timestamp in nanoseconds as a decimal string. */
export declare function currentTimestamp(): string
/** Validate a base58-encoded public key */
export declare function validatePubkey(s: string): boolean
/** Validate a base58-encoded hash */
export declare function validateHash(s: string): boolean
/**
 * Compute SHA256 hash from raw bytes.
 *
 * This is a raw utility and does not apply BULK order-ID canonicalization.
 */
export declare function computeOrderId(wincodeBytes: Buffer): string
/** Options for preparing a message */
export interface PrepareOptions {
  /** Network signature domain: "mainnet", "testnet", or "devnet" */
  signatureDomain: string
  /** Account public key (base58) - the trading account */
  account: string
  /** Signer public key (base58) - defaults to account if not provided */
  signer?: string
  /** Decimal-string u64 nonce; defaults to Unix nanoseconds if not provided */
  nonce?: string
}
/** Options for preparing a sub-account creation */
export interface CreateSubAccountOptions {
  /** Network signature domain: "mainnet", "testnet", or "devnet" */
  signatureDomain: string
  /** Account public key (base58) - the master trading account */
  account: string
  /** Signer public key (base58) - defaults to account if not provided */
  signer?: string
  /** Decimal-string u64 nonce; defaults to Unix nanoseconds if not provided */
  nonce?: string
  /** Optional initial margin amount. Default 0.0 */
  marginAmount?: number
}
/** Prepared message ready for external wallet signing */
export interface PreparedMessageOutput {
  /** Raw message bytes to sign (pass to wallet.signMessage()) */
  messageBytes: Buffer
  /** Message as base58 string */
  messageBase58: string
  /** Message as base64 string */
  messageBase64: string
  /** Message as hex string */
  messageHex: string
  /** Pre-computed order ID (base58) */
  orderId?: string
  /** Optional pre-computed order IDs for multi-order transactions. */
  orderIds?: Array<string>
  /** Actions JSON as string */
  actions: string
  /** Account public key (base58) */
  account: string
  /** Signer public key (base58) */
  signer: string
  /** Nonce used for this transaction */
  nonce: string
}
/**
 * Prepare a single order for external wallet signing
 *
 * Use this when you don't have access to the private key and need
 * to sign with an external wallet (like Phantom, Privy, etc).
 *
 * @example
 * ```typescript
 * const prepared = prepareOrder(order, { account: myPubkey });
 * const signature = await wallet.signMessage(prepared.messageBytes);
 * const signed = finalizeTransaction(prepared, signature);
 * ```
 */
export declare function prepareOrder(order: OrderInput, options: PrepareOptions): PreparedMessageOutput
/**
 * Prepare multiple orders - each becomes its own transaction (parallel)
 *
 * Each order gets independent confirmation/rejection.
 *
 * @example
 * ```typescript
 * const orders = [order1, order2, order3];
 * const prepared = prepareAllOrders(orders, { account: myPubkey });
 * // Sign each with wallet, then finalize
 * ```
 */
export declare function prepareAllOrders(orders: Array<OrderInput>, options: PrepareOptions): Array<PreparedMessageOutput>
/**
 * Prepare multiple orders as ONE atomic transaction
 *
 * Use for bracket orders (entry + stop loss + take profit).
 *
 * @example
 * ```typescript
 * const bracket = [entryOrder, stopLoss, takeProfit];
 * const prepared = prepareOrderGroup(bracket, { account: myPubkey });
 * const signature = await wallet.signMessage(prepared.messageBytes);
 * const signed = finalizeTransaction(prepared, signature);
 * ```
 */
export declare function prepareOrderGroup(orders: Array<OrderInput>, options: PrepareOptions): PreparedMessageOutput
/**
 * Prepare agent wallet creation for external signing
 *
 * @example
 * ```typescript
 * const prepared = prepareAgentWalletAuth(agentPubkey, false, { account: myPubkey });
 * const signature = await wallet.signMessage(prepared.messageBytes);
 * const signed = finalizeTransaction(prepared, signature);
 * ```
 */
export declare function prepareAgentWalletAuth(agentPubkey: string, delete: boolean, options: PrepareOptions): PreparedMessageOutput
/** Prepare a liquidator config update for external signing */
export declare function prepareUpdateLiquidatorConfig(config: LiquidatorConfigInput, options: PrepareOptions): PreparedMessageOutput
/** Prepare builder-code recipient approval for external signing */
export declare function prepareApproveCommissionFee(toPubkey: string, fee: number, options: PrepareOptions): PreparedMessageOutput
/** Prepare builder-code recipient approval for external signing */
export declare function prepareApproveBuilderCode(toPubkey: string, fee: number, options: PrepareOptions): PreparedMessageOutput
/** Prepare builder-code recipient revocation for external signing */
export declare function prepareRevokeCommissionFee(toPubkey: string, options: PrepareOptions): PreparedMessageOutput
/** Prepare builder-code recipient revocation for external signing */
export declare function prepareRevokeBuilderCode(toPubkey: string, options: PrepareOptions): PreparedMessageOutput
/** Prepare faucet request for external signing */
export declare function prepareFaucetRequest(options: PrepareOptions): PreparedMessageOutput
/** Options for preparing a margin transfer */
export interface TransferOptions {
  /** Network signature domain: "mainnet", "testnet", or "devnet" */
  signatureDomain: string
  /** Account public key (base58) - the trading account */
  account: string
  /** Signer public key (base58) - defaults to account if not provided */
  signer?: string
  /** Decimal-string u64 nonce; defaults to Unix nanoseconds if not provided */
  nonce?: string
  /** "internal" (default) or "external" */
  kind?: string
}
/** Prepare a margin transfer for external signing */
export declare function prepareTransferTx(fromPubkey: string, toPubkey: string, marginAmount: number, options: TransferOptions): PreparedMessageOutput
/** Prepare a sub-account removal for external signing */
export declare function prepareRemoveSubAccountTx(toRemove: string, options: PrepareOptions): PreparedMessageOutput
/** Prepare a sub-account rename for external signing */
export declare function prepareRenameSubAccountTx(subaccount: string, name: string, options: PrepareOptions): PreparedMessageOutput
/** Prepare a sub-account creation for external signing */
export declare function prepareCreateSubAccountTx(name: string, options: CreateSubAccountOptions): PreparedMessageOutput
/**
 * Finalize a prepared message with a signature from an external wallet
 *
 * @param prepared - The prepared message from prepare* functions
 * @param signature - Base58-encoded signature from wallet.signMessage()
 *
 * @example
 * ```typescript
 * const prepared = prepareOrder(order, { account: myPubkey });
 * const signature = await wallet.signMessage(prepared.messageBytes);
 * const signed = finalizeTransaction(prepared, signature);
 * // Now submit `signed` to the API
 * ```
 */
export declare function finalizePreparedTransaction(prepared: PreparedMessageOutput, signature: string): SignedTransactionOutput
/** Ed25519 keypair for signing transactions */
export declare class NativeKeypair {
  /** Generate a new random keypair */
  constructor()
  /** Create from base58-encoded secret key or full keypair */
  static fromBase58(s: string): NativeKeypair
  /** Create from raw bytes (32-byte secret or 64-byte full keypair) */
  static fromBytes(bytes: Buffer): NativeKeypair
  /** Get the public key as base58 string */
  get pubkey(): string
  /** Get the full keypair as base58 (64 bytes) */
  toBase58(): string
  /** Get the full keypair as bytes (64 bytes) */
  toBytes(): Buffer
  /** Get the secret key as bytes (32 bytes) */
  secretKey(): Buffer
  /** Clone the keypair */
  cloneKeypair(): NativeKeypair
}
/** High-performance transaction signer */
export declare class NativeSigner {
  /** Create a new signer from a keypair */
  constructor(keypair: NativeKeypair, signatureDomain: string)
  /** Create a signer from base58-encoded secret key */
  static fromBase58(s: string, signatureDomain: string): NativeSigner
  /** Create a signer with nonce management */
  static withNonceManager(keypair: NativeKeypair, strategy: string, signatureDomain: string): NativeSigner
  /** Get the signer's public key */
  get pubkey(): string
  /** Enable/disable single-order ID computation. */
  setComputeOrderId(enabled: boolean): void
  /** Enable/disable batch order ID computation for multi-order transactions. */
  setComputeBatchOrderIds(enabled: boolean): void
  /** Whether single-order ID computation is enabled. */
  computesOrderId(): boolean
  /** Whether batch order ID computation is enabled. */
  computesBatchOrderIds(): boolean
  /** Sign raw message bytes and return a base58 Ed25519 signature. */
  signBytes(message: Buffer): string
  /**
   * Sign a prepared message and finalize it into a signed transaction.
   *
   * This supports agent-wallet flows where prepared.account is the trading
   * account and prepared.signer is this NativeSigner's pubkey.
   */
  signPrepared(prepared: PreparedMessageOutput): SignedTransactionOutput
  /**
   * Sign a single order/cancel/cancelAll
   *
   * Most common use case - returns a single signed transaction.
   *
   * @example
   * ```typescript
   * const signed = signer.sign({ type: 'order', symbol: 'BTC-USD', isBuy: true, price: 100000, size: 0.1 });
   * ```
   */
  sign(order: OrderInput, nonce?: string | undefined | null): SignedTransactionOutput
  /**
   * Sign multiple orders - each becomes its own transaction (parallel)
   *
   * each order gets independent confirmation/rejection.
   * Automatically parallelizes when > 10 orders.
   *
   * @example
   * ```typescript
   * const orders = [order1, order2, order3];
   * const signedTxs = signer.signAll(orders); // Returns SignedTransaction[]
   * ```
   */
  signAll(orders: Array<OrderInput>, baseNonce?: string | undefined | null): Array<SignedTransactionOutput>
  /**
   * Sign multiple orders atomically in ONE transaction
   *
   * Use for bracket orders (entry + stop loss + take profit) where
   * all orders must succeed or fail together.
   *
   * @example
   * ```typescript
   * const bracket = [entryOrder, stopLoss, takeProfit];
   * const signed = signer.signGroup(bracket); // Returns single SignedTransaction
   * ```
   */
  signGroup(orders: Array<OrderInput>, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a faucet request (testnet only) */
  signFaucet(nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign agent wallet creation/deletion */
  signAgentWallet(agentPubkey: string, delete: boolean, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign builder-code recipient approval (`abc`) */
  signApproveCommissionFee(toPubkey: string, fee: number, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign builder-code recipient approval (`abc`) */
  signApproveBuilderCode(toPubkey: string, fee: number, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign builder-code recipient revocation (`rbc`) */
  signRevokeCommissionFee(toPubkey: string, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign builder-code recipient revocation (`rbc`) */
  signRevokeBuilderCode(toPubkey: string, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign user settings update */
  signUserSettings(maxLeverage: Array<LeverageSetting>, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a liquidator config update (`liq`) */
  signUpdateLiquidatorConfig(config: LiquidatorConfigInput, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign one or more oracle price updates (`px`) */
  signOraclePrices(oracles: Array<OraclePriceInput>, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a batch Pyth oracle update (`o`) */
  signPythOracle(oracles: Array<PythOraclePriceInput>, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a margin transfer between accounts */
  signTransfer(fromPubkey: string, toPubkey: string, marginAmount: number, kind?: string | undefined | null, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a sub-account creation (optional initial margin transfer) */
  signCreateSubAccount(name: string, marginAmount?: number | undefined | null, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a sub-account removal */
  signRemoveSubAccount(toRemove: string, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign a sub-account rename */
  signRenameSubAccount(subaccount: string, name: string, nonce?: string | undefined | null): SignedTransactionOutput
  /** Sign whitelist/un-whitelist faucet access (`whitelistFaucet`) */
  signWhitelistFaucet(targetPubkey: string, whitelist: boolean, nonce?: string | undefined | null): SignedTransactionOutput
  /** @deprecated Use sign() for single items, signAll() for batches, signGroup() for atomic */
  signOrder(orders: Array<OrderInput>, nonce?: string | undefined | null): SignedTransactionOutput
  /** @deprecated Use signAll() instead */
  signOrdersBatch(batches: Array<Array<OrderInput>>, baseNonce?: string | undefined | null): Array<SignedTransactionOutput>
}
